### ISSUE TITLE
Keep getting 'alert' is not a git command.

### ISSUE THREAD

**Issue by phaberest** [inca/git-alert#1]
I added git-alert as a dev dependency in my `package.json` and installed it using npm, but when I run `git alert install` I get:

```bash
git: 'alert' is not a git command. See 'git --help'.

Did you mean this?
	revert
```

Did I do any mistake?

**Comment by inca** [comment]
Right now it only works with globally installed via `npm i -g git-alert` or with env modifier like [npx](https://www.npmjs.com/package/npx).

**Comment by phaberest** [comment]
Thanks @inca I thought it could be installed as local dependency after reading the readme bonus.
